FROM node:18.13 AS builder

RUN mkdir -p /home/prodtrace
WORKDIR /home/prodtrace
COPY package*.json ./

RUN npm install -g @angular/cli
RUN npm install

COPY . .

RUN ng build  --configuration staging


FROM nginx:1.21.3-alpine

COPY --from=builder /home/prodtrace/dist/prod-trace /usr/share/nginx/html

EXPOSE 80 443
# ENTRYPOINT service nginx start && tail -f /dev/null
