version: '3'
services:
  prodtrace-frontend:
    image: 45.32.22.181:5000/prodtrace_frontend:latest
    #build: .
    ports:
      - "443:443"
    restart: always
    volumes:
      - /etc/letsencrypt/live/mobile.prodtrace.io/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/mobile.prodtrace.io/privkey.pem:/etc/ssl/certs/privkey.pem
